#!/bin/sh

checkfor() {
	command -v "$1" > /dev/null
}

if checkfor sudo; then
	sudo printf "" > /dev/null || printf "Root access required, run using sudo"
fi

if grep "swindles-arch-packages" /etc/pacman.conf > /dev/null; then
	"Repository already added!"
else
	cp /etc/pacman.conf /etc/pacman.conf.bak
	printf '\n[swindles-arch-packages]\nSigLevel = Optional DatabaseOptional\nServer = https://git.cbps.xyz/swindlesmccoop/$repo/raw/branch/master/$arch' >> /etc/pacman.conf
	sudo pacman -Syu
fi
