#!/bin/sh
REPO="swindles-arch-packages"

update () {
	rm -f $REPO*
	repo-add $REPO.db.tar.gz *.pkg.tar.zst
	unlink *.db
	unlink *.files
	mv $REPO.db* $REPO.db
	mv $REPO.files* $REPO.files
}

cd x86_64
update
cd ../any
update
cd ..

git add .
git commit -a
git push
